# Summary Notes: Eigenvalues & Eigenvectors

## 📚 Key Definitions in Linear Algebra

* **Linear Algebra:** The branch of mathematics concerning **vectors**, **vector spaces**, **matrices**, and **linear transformations**.
* **Vector:** A mathematical object that has both **magnitude** (size) and **direction**. It's often written as a column of numbers, e.g., $v = \begin{pmatrix} 1 \\ 1 \end{pmatrix}$.
    * **Zero Vector:** A vector where all entries are zero, e.g., $\begin{pmatrix} 0 \\ 0 \end{pmatrix}$.
    * **Non-zero Vector:** Any vector that is not the zero vector.
* **Scalar ($\lambda$):** A single number (not a vector), like 3, -1.5, or $\pi$.
* **Matrix ($A$):** A rectangular array of numbers, e.g., $A = \begin{pmatrix} 2 & 1 \\ 1 & 2 \end{pmatrix}$.
    * **$n \times n$ Matrix (Square Matrix):** A matrix with the same number of rows and columns.
* **Linear Transformation:** A "function" that takes a vector and maps it to a new vector. When represented by a matrix $A$, the transformation is $T(v) = Av$. This process can stretch, shrink, rotate, or shear the vector $v$.
* **Matrix-Vector Multiplication ($Av$):** The process of applying the transformation $A$ to the vector $v$.
* **Main Diagonal:** The set of entries in a square matrix running from the top-left corner to the bottom-right, e.g., the entries $a_{11}, a_{22}, \dots, a_{nn}$.
* **Identity Matrix ($I$):** A square matrix with 1s on the main diagonal and 0s everywhere else. It's the matrix equivalent of the number 1 (i.e., $Iv = v$ is true).
* **Determinant ($\det(A)$):** A special scalar value calculated from a square matrix. It tells you the "scaling factor" of the transformation on area or volume.
* **Invertible Matrix:** A square matrix $A$ that has an inverse ($A^{-1}$). This is only true if $\det(A) \neq 0$.
* **Matrix Inverse ($A^{-1}$):** A matrix that "undoes" the transformation of $A$. (i.e., $A^{-1}A = I$).

---

## 🎯 The Core Concept: Eigenvectors & Eigenvalues

* **Eigenvector ($v$):** A **non-zero** vector $v$ that, when a linear transformation $A$ is applied to it, **does not change its direction**.
* **Eigenvalue ($\lambda$):** The **scalar** $\lambda$ that represents *how much* the eigenvector $v$ was stretched or shrunk by the transformation $A$.

This relationship is defined by the fundamental equation:

$$Av = \lambda v$$

### Example

Let's test if $v = \begin{pmatrix} 1 \\ 1 \end{pmatrix}$ is an eigenvector for the matrix $A = \begin{pmatrix} 2 & 1 \\ 1 & 2 \end{pmatrix}$.

1.  **Apply the transformation $A$ to $v$:**
    $$Av = \begin{pmatrix} 2 & 1 \\ 1 & 2 \end{pmatrix} \begin{pmatrix} 1 \\ 1 \end{pmatrix} = \begin{pmatrix} 2(1) + 1(1) \\ 1(1) + 2(1) \end{pmatrix} = \begin{pmatrix} 3 \\ 3 \end{pmatrix}$$

2.  **Compare the result with the original $v$:**
    The result $\begin{pmatrix} 3 \\ 3 \end{pmatrix}$ is just $3 \times \begin{pmatrix} 1 \\ 1 \end{pmatrix}$.

3.  **Conclusion:**
    Since $Av = 3v$, we have matched the equation $Av = \lambda v$.
    * The **eigenvector** is $v = \begin{pmatrix} 1 \\ 1 \end{pmatrix}$.
    * The **eigenvalue** is $\lambda = 3$.

---

## 🔑 Properties of Eigenvalues (with Proofs)

To find eigenvalues, we solve the **Characteristic Equation**: $\det(A - \lambda I) = 0$. This equation is a polynomial, called the **Characteristic Polynomial**, and the eigenvalues ($\lambda_1, \dots, \lambda_n$) are its **roots** (solutions).

#### Property 1: Sum of Eigenvalues = Trace
* **Trace ($\text{trace}(A)$):** The sum of the elements on the **main diagonal** of a matrix.
* **Property:** $\sum_{i=1}^{n} \lambda_i = \text{trace}(A)$
* **Proof:** The characteristic polynomial $p(\lambda) = \det(A - \lambda I)$ has two forms:
    1.  **Factored by roots:** $p(\lambda) = (\lambda_1 - \lambda)\dots(\lambda_n - \lambda)$. Expanding this, the **coefficient** (number in front) of the $\lambda^{n-1}$ term is $(-1)^{n+1}(\sum \lambda_i)$.
    2.  **From determinant:** $p(\lambda) = \begin{vmatrix} a_{11}-\lambda & a_{12} & \dots \\ a_{21} & a_{22}-\lambda & \dots \\ \vdots & \vdots & \ddots \end{vmatrix}$. The only way to get a $\lambda^{n-1}$ term is from the product of the diagonals, which gives the term $\text{trace}(A) \cdot (-1)^{n-1}\lambda^{n-1}$.
    Equating the coefficients of $\lambda^{n-1}$ from both forms proves $\sum \lambda_i = \text{trace}(A)$.

#### Property 2: Product of Eigenvalues = Determinant
* **Property:** $\prod_{i=1}^{n} \lambda_i = \det(A)$
* **Proof:**
    1.  Start with the characteristic polynomial: $p(\lambda) = \det(A - \lambda I)$.
    2.  Set $\lambda = 0$: $p(0) = \det(A - 0 \cdot I) = \det(A)$.
    3.  Now use the root form: $p(\lambda) = (\lambda_1 - \lambda)(\lambda_2 - \lambda)\dots(\lambda_n - \lambda)$.
    4.  Set $\lambda = 0$: $p(0) = (\lambda_1 - 0)(\lambda_2 - 0)\dots(\lambda_n - 0) = \prod \lambda_i$.
    5.  Therefore, $\det(A) = \prod \lambda_i$.

#### Property 3: Eigenvalues of a Triangular Matrix
* **Triangular Matrix:** A square matrix where all entries *above* (lower triangular) or *below* (upper triangular) the main diagonal are zero. A **Diagonal Matrix** is one that is both.
* **Property:** The eigenvalues of a triangular matrix are its main diagonal entries.
* **Proof:** Let $A$ be triangular. Then $A - \lambda I$ is also triangular.
    $$A - \lambda I = \begin{pmatrix} a_{11}-\lambda & a_{12} & \dots \\ 0 & a_{22}-\lambda & \dots \\ \vdots & \vdots & \ddots \end{pmatrix}$$
    The determinant of a triangular matrix is just the product of its diagonal entries.
    $\det(A - \lambda I) = (a_{11}-\lambda)(a_{22}-\lambda)\dots(a_{nn}-\lambda) = 0$.
    The roots are clearly $\lambda_1 = a_{11}, \lambda_2 = a_{22}, \dots, \lambda_n = a_{nn}$.

#### Property 4: Eigenvalues of Matrix Powers ($A^k$)
* **Matrix Power ($A^k$):** The matrix $A$ multiplied by itself $k$ times ($A \cdot A \cdot \dots \cdot A$).
* **Property:** If $\lambda$ is an eigenvalue of $A$, then $\lambda^k$ is an eigenvalue of $A^k$.
* **Proof (by induction):**
    * **Base Case (k=1):** $A^1 v = \lambda^1 v$. True by definition.
    * **Inductive Step:** Assume $A^m v = \lambda^m v$ is true. We must show $A^{m+1} v = \lambda^{m+1} v$.
        $$A^{k+1} v = A(A^k v) \quad \text{(regroup power)}$$
        $$A^{k+1} v = A(\lambda^k v) \quad \text{(use assumption)}$$
        $$A^{k+1} v = \lambda^k (Av) \quad \text{(scalars move freely)}$$
        $$A^{k+1} v = \lambda^k (\lambda v) \quad \text{(use base case)}$$
        $$A^{k+1} v = \lambda^{k+1} v \quad \text{(Q.E.D.)}$$

#### Property 5: Eigenvalues of the Inverse ($A^{-1}$)
* **Property:** If $A$ is **invertible** with eigenvalue $\lambda$, then $A^{-1}$ has eigenvalue $\frac{1}{\lambda}$.
* **Proof:**
    * (Note: If $A$ is invertible, $\det(A) \neq 0$. By Property 2, this means no eigenvalue $\lambda$ can be zero.)
    1.  Start with the definition: $Av = \lambda v$.
    2.  Left-multiply by $A^{-1}$: $A^{-1}(Av) = A^{-1}(\lambda v)$.
    3.  Regroup: $(A^{-1}A)v = \lambda (A^{-1}v)$.
    4.  Simplify: $Iv = \lambda (A^{-1}v) \implies v = \lambda (A^{-1}v)$.
    5.  Since $\lambda \neq 0$, divide by $\lambda$: $\frac{1}{\lambda} v = A^{-1}v$.
    This is in the form $A^{-1}v = (\frac{1}{\lambda})v$, proving the property.

In [1]:
import numpy as np

# Set print options for better readability
np.set_printoptions(precision=5, suppress=True)

# --- Initial Setup ---
# Let's create a 3x3 matrix 'A'
# We'll use a matrix that has integer eigenvalues (0, -4, 3) to keep it clean.
A = np.array([
    [ 1,  2,  1],
    [ 6, -1,  0],
    [-1, -2, -1]
])

# 1. Find the eigenvalues
# np.linalg.eigvals() just returns the eigenvalues
eigvals = np.linalg.eigvals(A)

print("--- Initial Setup ---")
print("Our Matrix A:\n", A)
print("\nIts Eigenvalues (λ):\n", np.sort(eigvals))
print("-" * 30)

--- Initial Setup ---
Our Matrix A:
 [[ 1  2  1]
 [ 6 -1  0]
 [-1 -2 -1]]

Its Eigenvalues (λ):
 [-4.  0.  3.]
------------------------------


**1. Property 1: Sum of Eigenvalues = Trace**

**Property:** $\sum \lambda_i = \text{trace}(A)$

The **trace** is the sum of the main diagonal elements (1 + (-1) + (-1) = -1).

In [2]:
# --- Property 1: Trace ---
print("\n--- Property 1: Trace vs. Sum of Eigenvalues ---")

# Calculate the trace using NumPy
trace_A = np.trace(A)
print(f"Trace of A (from np.trace):     {trace_A}")

# Calculate the sum of eigenvalues
sum_eigvals = np.sum(eigvals)
print(f"Sum of eigenvalues (from np.sum): {sum_eigvals:.5f}")

# Check if they are equal (using np.isclose for floating point safety)
is_equal = np.isclose(trace_A, sum_eigvals)
print(f"\nProperty Verified: {is_equal}")


--- Property 1: Trace vs. Sum of Eigenvalues ---
Trace of A (from np.trace):     -1
Sum of eigenvalues (from np.sum): -1.00000

Property Verified: True


**2. Property 2: Product of Eigenvalues = Determinant**

**Property:** $\prod \lambda_i = \det(A)$

The **determinant** represents the volume scaling factor of the transformation. Since one of our eigenvalues is 0, the determinant should also be 0.

In [3]:
# --- Property 2: Determinant ---
print("\n--- Property 2: Determinant vs. Product of Eigenvalues ---")

# Calculate the determinant using NumPy
det_A = np.linalg.det(A)
print(f"Determinant of A (from np.linalg.det):     {det_A:.5f}")

# Calculate the product of eigenvalues
prod_eigvals = np.prod(eigvals)
print(f"Product of eigenvalues (from np.prod): {prod_eigvals:.5f}")

# Check if they are equal
is_equal = np.isclose(det_A, prod_eigvals)
print(f"\nProperty Verified: {is_equal}")


--- Property 2: Determinant vs. Product of Eigenvalues ---
Determinant of A (from np.linalg.det):     0.00000
Product of eigenvalues (from np.prod): -0.00000

Property Verified: True


**3. Property 3: Triangular Matrix Eigenvalues = Diagonal**

**Property:** The eigenvalues of a triangular matrix are its diagonal entries.

In [4]:
# --- Property 3: Triangular Matrix ---
print("\n--- Property 3: Triangular Matrix Eigenvalues ---")

# Create an upper triangular matrix 'B'
B = np.array([
    [5, 1, 7],
    [0, -2, 3],
    [0, 0, 4]
])

# Get the diagonal entries
diag_B = np.diag(B)
print(f"Triangular Matrix B:\n{B}")
print(f"\nDiagonal entries of B: {np.sort(diag_B)}")

# Get the eigenvalues of B
eigvals_B = np.linalg.eigvals(B)
print(f"Eigenvalues of B:    {np.sort(eigvals_B)}")

# Check if the sorted arrays are equal
is_equal = np.allclose(np.sort(diag_B), np.sort(eigvals_B))
print(f"\nProperty Verified: {is_equal}")


--- Property 3: Triangular Matrix Eigenvalues ---
Triangular Matrix B:
[[ 5  1  7]
 [ 0 -2  3]
 [ 0  0  4]]

Diagonal entries of B: [-2  4  5]
Eigenvalues of B:    [-2.  4.  5.]

Property Verified: True


**4. & 5. Setup for Powers and Inverse:**

For the next two properties, we need an invertible matrix (one that doesn't have a 0 eigenvalue). Let's use the simple $2 \times 2$ matrix from our original example.

In [5]:
# --- Setup for Properties 4 & 5 ---
M = np.array([
    [2, 1],
    [1, 2]
])
eigvals_M = np.linalg.eigvals(M)

print("\n--- Setup for Properties 4 & 5 ---")
print(f"New Invertible Matrix M:\n{M}")
print(f"Eigenvalues of M (λ): {eigvals_M}")
print("-" * 30)


--- Setup for Properties 4 & 5 ---
New Invertible Matrix M:
[[2 1]
 [1 2]]
Eigenvalues of M (λ): [3. 1.]
------------------------------


**4. Property 4: Eigenvalues of $A^k = \lambda^k$ Property:**

If $\lambda$ is an eigenvalue of $A$, then $\lambda^k$ is an eigenvalue of $A^k$. Let's test this with $k=3$.

In [6]:
# --- Property 4: Matrix Powers ---
print("\n--- Property 4: Eigenvalues of M^k ---")
k = 3

# 1. Eigenvalues of M^k
M_k = np.linalg.matrix_power(M, k)
eigvals_M_k = np.linalg.eigvals(M_k)
print(f"Eigenvalues of M^{k} (sorted): {np.sort(eigvals_M_k)}")

# 2. (Eigenvalues of M)^k
lambda_k = eigvals_M ** k
print(f"(Eigenvalues of M)^{k} (sorted): {np.sort(lambda_k)}")

# Check
is_equal = np.allclose(np.sort(eigvals_M_k), np.sort(lambda_k))
print(f"\nProperty Verified: {is_equal}")


--- Property 4: Eigenvalues of M^k ---
Eigenvalues of M^3 (sorted): [ 1. 27.]
(Eigenvalues of M)^3 (sorted): [ 1. 27.]

Property Verified: True


**5. Property 5: Eigenvalues of $A^{-1} = 1/\lambda$**

Property: If $\lambda$ is an eigenvalue of $A$, then $\frac{1}{\lambda}$ is an eigenvalue of $A^{-1}$.

In [7]:
# --- Property 5: Matrix Inverse ---
print("\n--- Property 5: Eigenvalues of M_inverse ---")

# 1. Eigenvalues of M_inverse
M_inv = np.linalg.inv(M)
eigvals_inv = np.linalg.eigvals(M_inv)
print(f"Eigenvalues of M_inv (sorted): {np.sort(eigvals_inv)}")

# 2. 1 / (Eigenvalues of M)
lambda_inv = 1 / eigvals_M
print(f"1 / (Eigenvalues of M) (sorted): {np.sort(lambda_inv)}")

# Check
is_equal = np.allclose(np.sort(eigvals_inv), np.sort(lambda_inv))
print(f"\nProperty Verified: {is_equal}")


--- Property 5: Eigenvalues of M_inverse ---
Eigenvalues of M_inv (sorted): [0.33333 1.     ]
1 / (Eigenvalues of M) (sorted): [0.33333 1.     ]

Property Verified: True
