**Generated By Google Gemini:**

# 📖 What is Singular Value Decomposition (SVD)?



In simple terms, **Singular Value Decomposition (SVD)** is a method of breaking down *any* matrix into a product of three simpler, more fundamental matrices.

Think of a matrix $A$ as a "transformation machine." You put a vector (a point in space) $\vec{x}$ into it, and it gives you a new vector $\vec{y}$ out: $A\vec{x} = \vec{y}$. This transformation can be complex: it might stretch, squash, rotate, and shear all at once.

SVD tells us that this complex machine, $A$, is *secretly* just a simple three-step process:

1.  **Step 1: A Rotation** (or reflection).
2.  **Step 2: A Scaling** (stretching or squashing along the new rotated axes).
3.  **Step 3: Another Rotation** (or reflection).

The SVD "recipe" is written as:
$$
A = U \Sigma V^T
$$

* **$A$** is your original $m \times n$ matrix.
* **$U$** is the $m \times m$ matrix for the final rotation.
* **$\Sigma$** (Sigma) is the $m \times n$ matrix for the scaling.
* **$V^T$** is the $n \times n$ matrix for the initial rotation.

To truly understand this, we must first understand the "ingredients": $U$, $\Sigma$, and $V^T$.

---

## 🥣 Part 1: The "Ingredients" Explained

Let's define the simple concepts that SVD is built from.

#### Matrix
A matrix is a grid of numbers that acts as a transformation machine.
* **Example:** $A = \begin{bmatrix} 2 & 1 \\ 1 & 2 \end{bmatrix}$.
    If you put the vector $\vec{x} = \begin{bmatrix} 1 \\ 0 \end{bmatrix}$ (a point at x=1, y=0) into it, you get:
    $A\vec{x} = \begin{bmatrix} 2 & 1 \\ 1 & 2 \end{bmatrix} \begin{bmatrix} 1 \\ 0 \end{bmatrix} = \begin{bmatrix} 2 \\ 1 \end{bmatrix}$.
    The matrix $A$ moved the point $(1, 0)$ to $(2, 1)$. This is a stretch and a shear.

#### Matrix Transpose ($A^T$)
The transpose "flips" a matrix along its main diagonal. Rows become columns, and columns become rows.
* **Example:** If $A = \begin{bmatrix} 2 & 1 \\ 1 & 2 \end{bmatrix}$, then $A^T = \begin{bmatrix} 2 & 1 \\ 1 & 2 \end{bmatrix}$. (This matrix is *symmetric*).
* **Example 2:** If $B = \begin{bmatrix} 1 & 2 & 3 \\ 4 & 5 & 6 \end{bmatrix}$, then $B^T = \begin{bmatrix} 1 & 4 \\ 2 & 5 \\ 3 & 6 \end{bmatrix}$.

#### Diagonal Matrix
A matrix where all entries are zero *except* for the values on the main diagonal. Its only job is to **scale** (stretch or squash) space along the standard axes (the x-axis, y-axis, etc.).
* **Example:** $D = \begin{bmatrix} 3 & 0 \\ 0 & 0.5 \end{bmatrix}$.
    This matrix transforms a vector $\begin{bmatrix} x \\ y \end{bmatrix}$ into $\begin{bmatrix} 3x \\ 0.5y \end{bmatrix}$. It stretches space by 3x along the x-axis and squashes it by 0.5x along the y-axis.

#### Orthogonal Matrix ($Q$)
This is the most important ingredient. It represents a **pure rotation or reflection**.
* **Geometric Property:** It **preserves lengths and angles**.
    * If you take a vector $\vec{x}$, its length *does not change* when you transform it with $Q$.
    * If you take two perpendicular vectors, $\vec{x}$ and $\vec{y}$, their transformed versions ($Q\vec{x}$ and $Q\vec{y}$) will *still be perpendicular*.
* **Mathematical Property:** Its columns are **orthonormal**.
    * *Ortho-* (Orthogonal): Each column vector is perpendicular (at a 90° angle) to every other column vector.
    * *-normal* (Normalized): Each column vector has a length of 1.
* **The Key Test:** A matrix $Q$ is orthogonal if its transpose is also its inverse.
    > $Q^T Q = I$ (the identity matrix)
    This means "undoing" the rotation ($Q^{-1}$) is as simple as "flipping" it ($Q^T$).
* **Example:** $Q = \begin{bmatrix} 0 & -1 \\ 1 & 0 \end{bmatrix}$.
    This is a 90° counter-clockwise rotation. Let's test it on $\begin{bmatrix} 1 \\ 0 \end{bmatrix}$ (the x-axis vector):
    $\begin{bmatrix} 0 & -1 \\ 1 & 0 \end{bmatrix} \begin{bmatrix} 1 \\ 0 \end{bmatrix} = \begin{bmatrix} 0 \\ 1 \end{bmatrix}$ (the y-axis vector).
    It rotated the x-axis to the y-axis, as expected.

---

## 🍳 Part 2: The "Recipe" - Deconstructing $A = U \Sigma V^T$

Now let's look at the three parts of the SVD formula. Remember our story: **Rotate 1, then Scale, then Rotate 2.**

#### 1. $V^T$: The First Rotation (The "Input Aligner")
* **What it is:** $V^T$ is an $n \times n$ **orthogonal matrix**.
* **What it does:** It takes your input vector and **rotates** it.
* **Why?** It rotates the input space so that its *most important directions* are perfectly aligned with the standard axes (x, y, z...). These "most important directions" are called the **Right Singular Vectors**, and they are the columns of $V$ (the rows of $V^T$).
* **Analogy:** Imagine your transformation $A$ is a pasta machine that squashes dough flat. $V^T$ is the first step: *rotating the ball of dough* so it's aligned with the machine's rollers.

#### 2. $\Sigma$: The Scaling (The "Stretching & Squashing")
* **What it is:** $\Sigma$ is an $m \times n$ **diagonal matrix**.
* **What it does:** It scales the rotated vector along each axis. The diagonal entries are the **Singular Values** ($\sigma_1, \sigma_2, \sigma_3, ...$).
* **Key Details:**
    * These values are always positive ($\ge 0$).
    * They are sorted by "importance": $\sigma_1 \ge \sigma_2 \ge \sigma_3 \ge ...$
    * $\sigma_1$ is the "most important" scaling factor, and $\sigma_2$ is the second most, and so on.
* **Analogy:** This *is* the pasta machine's rollers. It squashes the dough (vector) along the 2nd axis (e.g., $\sigma_2 = 0.1$) and stretches it along the 1st axis (e.g., $\sigma_1 = 4$). If a singular value is 0, it means that direction is *completely flattened*.

#### 3. $U$: The Second Rotation (The "Output Aligner")
* **What it is:** $U$ is an $m \times m$ **orthogonal matrix**.
* **What it does:** It takes the stretched-and-squashed vector and **rotates** it to its final position in the output space.
* **Why?** The scaling step left our vector aligned with the axes. $U$ rotates it to whatever final orientation the original matrix $A$ required. The columns of $U$ are called the **Left Singular Vectors** and they form the new, principal axes of the *output*.
* **Analogy:** The flattened pasta comes out of the machine. $U$ is the step where you *rotate* the sheet of pasta to place it on the drying rack.

---

## 🎨 Part 3: The Geometric Picture (Circle to Ellipse)

This is the most powerful way to understand SVD.

**Imagine transforming a unit circle** (all 2D vectors with length 1).



1.  **Start:** We have a unit circle. Its main axes are the x-axis $\begin{bmatrix} 1 \\ 0 \end{bmatrix}$ and y-axis $\begin{bmatrix} 0 \\ 1 \end{bmatrix}$.
2.  **Apply $V^T$ (Rotate 1):** $V^T$ rotates the circle. It's still a perfect circle. But its axes are now aligned with the new **right singular vectors** ($v_1, v_2$).
3.  **Apply $\Sigma$ (Scale):** $\Sigma$ scales this rotated circle. It stretches by $\sigma_1$ along the $v_1$ axis and by $\sigma_2$ along the $v_2$ axis. This transforms the circle into an **ellipse**. The lengths of the ellipse's main axes are exactly $\sigma_1$ and $\sigma_2$.
4.  **Apply $U$ (Rotate 2):** $U$ takes this new ellipse (which is currently aligned with $v_1, v_2$) and **rotates** it into its final position. The final axes of the ellipse point along the **left singular vectors** ($u_1, u_2$).

**SVD, in essence, finds the directions in your input space ($V$) that map perfectly to perpendicular directions in your output space ($U$), and tells you how much each direction was stretched or squashed ($\Sigma$).**

---

## 🔬 Part 4: Key Properties & Why SVD is So Useful

SVD isn't just a mathematical curiosity; its properties are the reason it's used in data science, image compression, and machine learning.

#### 1. Relation to Eigenvalues (The "Proof" of SVD)
This property shows *how* we find $U$, $\Sigma$, and $V$.
* **Property:** The squares of the singular values ($\sigma_i^2$) are the **eigenvalues** of the matrix $A^T A$. The columns of $V$ are the **eigenvectors** of $A^T A$.
* **Proof Sketch:**
    $A = U \Sigma V^T$
    $A^T = (U \Sigma V^T)^T = V \Sigma^T U^T$
    Let's compute $A^T A$:
    $A^T A = (V \Sigma^T U^T) (U \Sigma V^T)$
    Since $U$ is orthogonal, $U^T U = I$ (the identity matrix), so they cancel out:
    $A^T A = V (\Sigma^T \Sigma) V^T$
    $\Sigma^T \Sigma$ is just a square diagonal matrix with $\sigma_i^2$ on its diagonal. Let's call it $D$.
    $A^T A = V D V^T$
    This is the *definition* of eigendecomposition. It proves that **$V$ is the matrix of eigenvectors for $A^T A$** and **$D$ is the matrix of its eigenvalues (which are $\sigma_i^2$)**.
    *(A similar proof shows $U$ is the matrix of eigenvectors for $A A^T$)*.
* **Example:** If $A = \begin{bmatrix} 1 & 1 \\ 0 & 0 \end{bmatrix}$, then $A^T A = \begin{bmatrix} 1 & 0 \\ 1 & 0 \end{bmatrix} \begin{bmatrix} 1 & 1 \\ 0 & 0 \end{bmatrix} = \begin{bmatrix} 1 & 1 \\ 1 & 1 \end{bmatrix}$. The eigenvalues of this matrix are $\lambda_1 = 2$ and $\lambda_2 = 0$.
    This means our singular values are $\sigma_1 = \sqrt{2}$ and $\sigma_2 = \sqrt{0} = 0$.

#### 2. Rank
* **Property:** The **rank** of a matrix $A$ (the number of independent dimensions it outputs) is equal to the number of **non-zero singular values**.
* **Intuition:** The singular values are the "magnitudes" of the transformation's actions. If a singular value is 0, it means the machine *completely flattens* that direction. The rank is the count of directions that *survive* this flattening.
* **Example:** For $A = \begin{bmatrix} 1 & 1 \\ 0 & 0 \end{bmatrix}$, our singular values were $\sqrt{2}$ and $0$. We have **one** non-zero singular value, so the rank is **1**. This makes sense: the matrix $A$ transforms *every* 2D point onto the x-axis, which is a 1D line.

#### 3. Determinant
* **Property:** For a square matrix $A$, the absolute value of its determinant is the product of all its singular values: $|\det(A)| = \sigma_1 \cdot \sigma_2 \cdot ... \cdot \sigma_n$.
* **Intuition:** The determinant measures how much a transformation changes *volume* (or area in 2D). The rotations $U$ and $V^T$ don't change volume ($\det = \pm 1$). The scaling matrix $\Sigma$ *is* the change in volume. The new volume is just the product of the scaling factors in each direction ($\sigma_1 \times \sigma_2 \times ...$).
* **Example:** For $A = \begin{bmatrix} 1 & 1 \\ 0 & 0 \end{bmatrix}$, $\det(A) = (1)(0) - (1)(0) = 0$. The singular values are $\sqrt{2}$ and $0$. Their product is $\sqrt{2} \cdot 0 = 0$. It matches.

#### 4. Low-Rank Approximation (The "Magic" Property)
* **Property:** The "best" rank-$k$ approximation of $A$ is found by taking its SVD and setting all but the largest $k$ singular values to zero.
* **The Math:** $A$ can also be written as a sum:
    $A = \sigma_1 u_1 v_1^T + \sigma_2 u_2 v_2^T + \sigma_3 u_3 v_3^T + ...$
    Since $\sigma_1 \ge \sigma_2 \ge ...$, the first term is the *most important part* of the matrix, the second term is the next most important, and so on.
* **Approximation:** To get a "good enough" approximation of $A$, you just add up the first $k$ terms:
    $A_k = \sigma_1 u_1 v_1^T + ... + \sigma_k u_k v_k^T$
* **Application (Image Compression):** An image is just a matrix of pixel values. You compute its SVD. You might find it has 500 singular values. By keeping only the first 50 (the $k=50$ approximation), you can store just those 50 $\sigma$'s and their corresponding $u, v$ vectors. This uses *far* less data, but the reconstructed image $A_{50}$ looks almost identical to the original. You've thrown away the "noise" and "tiny details" (the small singular values) and kept the "important structure."

## Summary

Here are the formal mathematical formulas for the properties of Singular Value Decomposition (SVD).

### 1. The SVD Decomposition

Let $A$ be an $m \times n$ matrix.

* **Matrix Form:**
    $$
    A = U \Sigma V^T
    $$
    Where $U$ is an $m \times m$ orthogonal matrix, $\Sigma$ is an $m \times n$ diagonal matrix, and $V^T$ is an $n \times n$ orthogonal matrix.

* **Outer Product Form (Sum):**
    $$
    A = \sum_{i=1}^{r} \sigma_i \vec{u}_i \vec{v}_i^T
    $$
    Where $r = \text{rank}(A)$, $\sigma_i$ are the singular values, $\vec{u}_i$ (columns of $U$) are the left singular vectors, and $\vec{v}_i$ (columns of $V$) are the right singular vectors.

---

### 2. Eigenvalue Relation

* **Right Singular Vectors ($V$):** The columns of $V$ ($\vec{v}_i$) are the eigenvectors of $A^T A$. The eigenvalues of $A^T A$ are the squares of the singular values ($\sigma_i^2$).
    $$
    A^T A \vec{v}_i = \sigma_i^2 \vec{v}_i
    $$

* **Left Singular Vectors ($U$):** The columns of $U$ ($\vec{u}_i$) are the eigenvectors of $A A^T$. The non-zero eigenvalues of $A A^T$ are also the squares of the singular values ($\sigma_i^2$).
    $$
    A A^T \vec{u}_i = \sigma_i^2 \vec{u}_i
    $$

---

### 3. Rank

The rank of $A$, denoted $r$, is equal to the number of non-zero singular values.
$$
\text{rank}(A) = r = |\{i \mid \sigma_i > 0\}|
$$

---

### 4. Determinant (for square $n \times n$ matrices)

The absolute value of the determinant of a square matrix $A$ is the product of all its singular values.
$$
|\det(A)| = \prod_{i=1}^{n} \sigma_i
$$

More precisely, since $\det(U) = \pm 1$ and $\det(V^T) = \pm 1$:
$$
\det(A) = \det(U) \det(V^T) \prod_{i=1}^{n} \sigma_i
$$

---

### 5. Low-Rank Approximation (Eckart-Young Theorem)

The best rank-$k$ approximation of $A$, denoted $A_k$, is the sum of the first $k$ outer products.
$$
A_k = \sum_{i=1}^{k} \sigma_i \vec{u}_i \vec{v}_i^T
$$
This matrix $A_k$ minimizes the Frobenius norm of the difference with $A$:
$$
A_k = \underset{B \text{ s.t. rank}(B)=k}{\arg\min} \|A - B\|_F
$$

## Proof Of Properties of SVD With Python, Numpy

## ⚙️ Part 1: Setup

This part just sets up our experiment. We import the `numpy` library (the standard for numerical operations) and define two test matrices.
* `A_sq`: A 3x3 **square matrix**. We'll use this to test properties that only apply to square matrices, like the determinant.
* `A_rect`: A 4x2 **rectangular matrix**. This is a more general case and is perfect for testing rank and the eigenvalue relationships.

In [2]:
import numpy as np

# Set print options for cleaner output (fewer decimals, suppress scientific notation)
np.set_printoptions(precision=4, suppress=True)

# -----------------------------------------------------------------
# Part 1: Setup
# -----------------------------------------------------------------

# A square matrix (for determinant property)
A_sq = np.array([[1, 2, 3], 
                 [4, 5, 6], 
                 [7, 8, 10]]) 

# A rectangular matrix (for rank and non-square properties)
A_rect = np.array([[1, 2], 
                   [3, 4], 
                   [5, 6],
                   [7, 8]])

print("--- Original Square Matrix A_sq (3x3) ---")
print(A_sq)
print("\n--- Original Rectangular Matrix A_rect (4x2) ---")
print(A_rect)

--- Original Square Matrix A_sq (3x3) ---
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8 10]]

--- Original Rectangular Matrix A_rect (4x2) ---
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


## 🔬 Part 2: Proof of Property 1 (Eigenvalues)

**Property:** The **eigenvalues** of $A^T A$ are the **squares of the singular values** ($\sigma^2$).

**Explanation of the Proof:**
This proof shows the deep connection between eigenvalues and singular values. We test this on our rectangular matrix `A_rect`.

1.  **Get Singular Values ($s$):** First, we get the SVD of `A_rect` and find its singular values `s_rect`. We square them to get $\sigma^2$.
2.  **Get Eigenvalues of $A^T A$ ($\lambda$):** Second, we *independently* calculate the matrix $A^T A$ and find *its* eigenvalues.
3.  **Compare:** The `np.allclose` function returns `True`, confirming the two lists of numbers are identical.

We then repeat this for $A A^T$ (a larger 4x4 matrix). Its non-zero eigenvalues also perfectly match $\sigma^2$, with the extra $m-n = 2$ eigenvalues being zero, just as theory predicts.

In [3]:
# -----------------------------------------------------------------
# Part 2: Proof of Property 1 (Eigenvalues)
# -----------------------------------------------------------------

print("\n\n--- Property 1: SVD and Eigenvalues (using 4x2 matrix A_rect) ---")

# 1. Get singular values from SVD and square them
U_rect, s_rect, Vt_rect = np.linalg.svd(A_rect)
s_rect_squared = s_rect**2

print(f"Singular values (s) from SVD:            {s_rect}")
print(f"Singular values squared (s^2):           {s_rect_squared}")

# 2. Get eigenvalues from A.T @ A
AtA = A_rect.T @ A_rect
eigvals_AtA, eigvecs_V = np.linalg.eig(AtA)

# Sort both descending for comparison
s_rect_squared_sorted = np.sort(s_rect_squared)[::-1]
eigvals_AtA_sorted = np.sort(np.real(eigvals_AtA))[::-1]

print(f"\nEigenvalues of A_rect.T @ A_rect (2x2):  {eigvals_AtA_sorted}")

# 3. Compare the results
print(f"Eigenvalues of A^T@A match s^2:          {np.allclose(s_rect_squared_sorted, eigvals_AtA_sorted)}")

# (Optional) Show the same for A @ A.T
AAt = A_rect @ A_rect.T
eigvals_AAt, eigvecs_U = np.linalg.eig(AAt)
eigvals_AAt_sorted = np.sort(np.real(eigvals_AAt))[::-1] 
print(f"\nEigenvalues of A_rect @ A_rect.T (4x4):  {eigvals_AAt_sorted}")



--- Property 1: SVD and Eigenvalues (using 4x2 matrix A_rect) ---
Singular values (s) from SVD:            [14.2691  0.6268]
Singular values squared (s^2):           [203.6071   0.3929]

Eigenvalues of A_rect.T @ A_rect (2x2):  [203.6071   0.3929]
Eigenvalues of A^T@A match s^2:          True

Eigenvalues of A_rect @ A_rect.T (4x4):  [203.6071   0.3929  -0.      -0.    ]


## 🔬 Part 3: Proof of Property 2 (Determinant)

**Property:** For a square matrix, the **absolute value of the determinant** is the **product of the singular values**.

**Explanation of the Proof:**
This proof uses our square matrix `A_sq`.

1.  **Direct Determinant:** We use `np.linalg.det(A_sq)` to find the determinant *directly*.
2.  **SVD Product:** We get the singular values `s_sq` and multiply them all together using `np.prod(s_sq)`.
3.  **Compare:** The values are identical. This proves that the determinant (which measures the "volume change" of a transformation) is fundamentally just the product of the scaling factors ($\sigma_i$) from the SVD.

In [4]:
# -----------------------------------------------------------------
# Part 3: Proof of Property 2 (Determinant)
# -----------------------------------------------------------------

print("\n\n--- Property 2: Determinant (using 3x3 matrix A_sq) ---")

# Get SVD components
U_sq, s_sq, Vt_sq = np.linalg.svd(A_sq)

# 1. Direct calculation
det_direct = np.linalg.det(A_sq)
abs_det_direct = np.abs(det_direct)
print(f"Direct calculation: |det(A_sq)| =       {abs_det_direct:.4f}")

# 2. SVD calculation
prod_s = np.prod(s_sq)
print(f"From SVD: product(s) =                {prod_s:.4f}")

# 3. Compare
print(f"|det(A)| matches product(s):           {np.allclose(abs_det_direct, prod_s)}")



--- Property 2: Determinant (using 3x3 matrix A_sq) ---
Direct calculation: |det(A_sq)| =       3.0000
From SVD: product(s) =                3.0000
|det(A)| matches product(s):           True


## 🔬 Part 4: Proof of Property 3 (Rank)

**Property:** The **rank** of a matrix is the number of **non-zero singular values**.

**Explanation of the Proof:**
This proof uses our rectangular matrix `A_rect`.

1.  **Direct Rank:** We use `np.linalg.matrix_rank(A_rect)` to ask NumPy for the rank directly.
2.  **SVD Rank:** We look at the singular values `s_rect`. We count how many are greater than a tiny tolerance (to avoid floating-point errors).
3.  **Compare:** Both methods agree. The rank (the number of "dimensions" in the output) is exactly the number of non-zero scaling factors.

In [5]:
# -----------------------------------------------------------------
# Part 4: Proof of Property 3 (Rank)
# -----------------------------------------------------------------

print("\n\n--- Property 3: Rank (using 4x2 matrix A_rect) ---")

# 1. Direct rank
rank_direct = np.linalg.matrix_rank(A_rect)
print(f"Direct rank from np.linalg.matrix_rank: {rank_direct}")

# 2. Rank from SVD
# (s_rect was [14.2691  0.6268])
tol = np.finfo(s_rect.dtype).eps * max(A_rect.shape)
rank_from_svd = np.sum(s_rect > tol)
print(f"Rank from SVD (count of s > tol):    {rank_from_svd}")

# 3. Compare
print(f"Ranks match:                         {rank_direct == rank_from_svd}")



--- Property 3: Rank (using 4x2 matrix A_rect) ---
Direct rank from np.linalg.matrix_rank: 2
Rank from SVD (count of s > tol):    2
Ranks match:                         True


## 🔬 Part 5: Proof of Property 4 (Low-Rank Approximation)

**Property:** The best **rank-k approximation** of $A$ is $A_k = U \Sigma_k V^T$, where $\Sigma_k$ is the $\Sigma$ matrix with all but the $k$ largest singular values set to zero.

**Explanation of the Proof:**
This proof is in two parts. First, we show that $U \Sigma V^T$ perfectly rebuilds $A$. Second, we show that $U \Sigma_k V^T$ creates a new matrix of rank $k$.

1.  **Part 1: Reconstruction:** We use the "economy" SVD for easier math. We take `U_econ`, `s_econ`, and `Vt_econ`, reassemble them (turning the `s_econ` array into a 2D `Sigma_full` matrix), and multiply them. This proves $A = U \Sigma V^T$ is true.
2.  **Part 2: Approximation:** We decide we want a **rank-1** approximation (so $k=1$).
    * We copy the singular values `s_econ`.
    * We set all but the first $k=1$ values to zero, giving `s_k = [14.2691, 0.]`.
    * We build a new matrix, `A_k1`, using these *modified* singular values.
3.  **Verify Rank:** We check the rank of our new matrix `A_k1` using `np.linalg.matrix_rank`.
    * Output: The rank is **1**. This proves that the SVD method successfully created a new matrix of exactly the rank we asked for.

In [7]:
# -----------------------------------------------------------------
# Part 5: Proof of Property 4 (Low-Rank Approximation)
# -----------------------------------------------------------------

print("\n\n--- Property 4: Low-Rank Approximation (using 4x2 matrix A_rect) ---")

# Use 'economy' SVD for easier reconstruction
U_econ, s_econ, Vt_econ = np.linalg.svd(A_rect, full_matrices=False)
# U_econ is 4x2, s_econ is (2,), Vt_econ is 2x2.

# 1. --- Part 1: Prove Reconstruction Works ---
Sigma_full = np.diag(s_econ)
A_recon = U_econ @ Sigma_full @ Vt_econ
print("\nFull Reconstructed A_rect (from economy SVD):")
print(A_recon)
print(f"Reconstruction matches original: {np.allclose(A_rect, A_recon)}")


# 2. --- Part 2: Create a Rank-1 Approximation ---
k = 1
s_k = np.copy(s_econ)
s_k[k:] = 0 # Zero out all but the first k singular values
Sigma_k = np.diag(s_k)

A_k1 = U_econ @ Sigma_k @ Vt_econ
print(f"\nRank-{k} Approximation (A_k1):")
print(A_k1)

# 3. --- Verify the Rank of the New Matrix ---
rank_k1 = np.linalg.matrix_rank(A_k1)
print(f"Rank of A_k1 is: {rank_k1} (as expected)")



--- Property 4: Low-Rank Approximation (using 4x2 matrix A_rect) ---

Full Reconstructed A_rect (from economy SVD):
[[1. 2.]
 [3. 4.]
 [5. 6.]
 [7. 8.]]
Reconstruction matches original: True

Rank-1 Approximation (A_k1):
[[1.3956 1.6692]
 [3.2026 3.8306]
 [5.0097 5.9919]
 [6.8167 8.1533]]
Rank of A_k1 is: 1 (as expected)
